wandb_version: 1

activation:
  value: RELU
batch_size:
  value: 32
initializer:
  value: HE
learning_rate:
  value: 0.001
max_epochs:
  value: 5
num_hidden_neurons:
  value: 64
num_layers:
  value: 4
optimizer:
  value: MGD
weight_decay:
  value: 0.0005
