_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.1
        t:
            "1":
                - 2
                - 3
                - 49
                - 55
            "2":
                - 2
                - 3
                - 49
                - 55
            "3":
                - 2
                - 14
                - 16
                - 17
                - 23
                - 55
            "4": 3.12.1
            "5": 0.19.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
activation:
    value: TANH
batch_size:
    value: 64
initializer:
    value: XAVIER
learning_rate:
    value: 0.001
loss:
    value: CROSS
max_epochs:
    value: 10
num_hidden_layers:
    value: 3
num_hidden_neurons:
    value: 64
num_layers:
    value: 3
optimizer:
    value: NAG
weight_decay:
    value: 0.5
