_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.1
        t:
            "1":
                - 2
                - 3
                - 49
                - 55
            "2":
                - 2
                - 3
                - 49
                - 55
            "3":
                - 2
                - 14
                - 16
                - 17
                - 23
                - 55
            "4": 3.12.1
            "5": 0.19.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
activation:
    value: TANH
activation_func:
    value: SIGMOID
batch_size:
    value: 32
epochs:
    value: 5
hidden_layers:
    value: 3
hidden_neurons:
    value: 128
init_method:
    value: XAVIER
initializer:
    value: XAVIER
layers:
    value: 3
learning_rate:
    value: 0.001
loss_function:
    value: CROSS
max_epochs:
    value: 5
optimizer:
    value: RMSPROP
weight_decay:
    value: 0.5
