wandb_version: 1

activation_func:
  value: RELU
batch_size:
  value: 32
epochs:
  value: 5
hidden_neurons:
  value: 64
init_method:
  value: XAVIER
layers:
  value: 4
learning_rate:
  value: 0.0001
optimizer:
  value: MGD
weight_decay:
  value: 0
