wandb_version: 1

activation_func:
  value: RELU
batch_size:
  value: 32
epochs:
  value: 5
hidden_neurons:
  value: 32
init_method:
  value: XAVIER
layers:
  value: 2
learning_rate:
  value: 0.001
optimizer:
  value: SGD
weight_decay:
  value: 0.5
