wandb_version: 1

activation_func:
  value: SIGMOID
batch_size:
  value: 16
epochs:
  value: 5
hidden_neurons:
  value: 32
init_method:
  value: RANDOM
layers:
  value: 3
learning_rate:
  value: 0.0001
optimizer:
  value: MGD
weight_decay:
  value: 0.0005
