wandb_version: 1

activation_func:
  value: RELU
batch_size:
  value: 64
epochs:
  value: 10
hidden_neurons:
  value: 32
init_method:
  value: RANDOM
layers:
  value: 2
learning_rate:
  value: 0.001
optimizer:
  value: SGD
weight_decay:
  value: 0.0005
