wandb_version: 1

activation_func:
  value: RELU
batch_size:
  value: 64
epochs:
  value: 10
hidden_neurons:
  value: 64
init_method:
  value: XAVIER
layers:
  value: 2
learning_rate:
  value: 0.0001
optimizer:
  value: SGD
weight_decay:
  value: 0.5
