wandb_version: 1

activation_func:
  value: TANH
batch_size:
  value: 32
epochs:
  value: 10
hidden_neurons:
  value: 128
init_method:
  value: XAVIER
layers:
  value: 4
learning_rate:
  value: 0.0001
optimizer:
  value: MGD
weight_decay:
  value: 0.0005
