wandb_version: 1

activation_func:
  value: SIGMOID
batch_size:
  value: 64
epochs:
  value: 10
hidden_neurons:
  value: 64
init_method:
  value: XAVIER
layers:
  value: 3
learning_rate:
  value: 0.001
optimizer:
  value: RMSPROP
weight_decay:
  value: 0
