wandb_version: 1

activation_func:
  value: SIGMOID
batch_size:
  value: 32
epochs:
  value: 5
hidden_neurons:
  value: 32
init_method:
  value: RANDOM
layers:
  value: 4
learning_rate:
  value: 0.001
optimizer:
  value: RMSPROP
weight_decay:
  value: 0
