wandb_version: 1

activation_func:
  value: SIGMOID
batch_size:
  value: 16
epochs:
  value: 10
hidden_neurons:
  value: 128
init_method:
  value: XAVIER
layers:
  value: 3
learning_rate:
  value: 0.0001
optimizer:
  value: SGD
weight_decay:
  value: 0
