wandb_version: 1

activation_func:
  value: TANH
batch_size:
  value: 64
epochs:
  value: 5
hidden_neurons:
  value: 32
init_method:
  value: XAVIER
layers:
  value: 3
learning_rate:
  value: 0.001
optimizer:
  value: ADAM
weight_decay:
  value: 0.5
