wandb_version: 1

activation_func:
  value: TANH
batch_size:
  value: 64
epochs:
  value: 5
hidden_neurons:
  value: 64
init_method:
  value: XAVIER
layers:
  value: 3
learning_rate:
  value: 0.0001
optimizer:
  value: NGD
weight_decay:
  value: 0.5
