wandb_version: 1

activation_func:
  value: RELU
batch_size:
  value: 16
epochs:
  value: 5
hidden_neurons:
  value: 128
init_method:
  value: XAVIER
layers:
  value: 4
learning_rate:
  value: 0.0001
optimizer:
  value: ADAM
weight_decay:
  value: 0.5
