_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 2
                - 14
                - 16
                - 17
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
activation:
    value: SIGMOID
batch_size:
    value: 32
initializer:
    value: XAVIER
learning_rate:
    value: 0.001
loss:
    value: CROSS
max_epochs:
    value: 5
num_hidden_layers:
    value: 3
num_hidden_neurons:
    value: 128
num_layers:
    value: 3
optimizer:
    value: NAG
weight_decay:
    value: 0.0005
