wandb_version: 1

activation_func:
  value: TANH
batch_size:
  value: 16
epochs:
  value: 10
hidden_neurons:
  value: 64
init_method:
  value: RANDOM
layers:
  value: 2
learning_rate:
  value: 0.001
optimizer:
  value: NGD
weight_decay:
  value: 0.0005
