wandb_version: 1

activation_func:
  value: SIGMOID
batch_size:
  value: 16
epochs:
  value: 5
hidden_neurons:
  value: 64
init_method:
  value: XAVIER
layers:
  value: 4
learning_rate:
  value: 0.0001
optimizer:
  value: RMSPROP
weight_decay:
  value: 0
