wandb_version: 1

activation:
  value: RELU
batch_size:
  value: 32
initializer:
  value: RANDOM
learning_rate:
  value: 0.001
max_epochs:
  value: 5
num_hidden_neurons:
  value: 128
num_layers:
  value: 3
optimizer:
  value: NAG
weight_decay:
  value: 0
