wandb_version: 1

activation:
  value: SIGMOID
batch_size:
  value: 16
initializer:
  value: RANDOM
learning_rate:
  value: 0.0001
max_epochs:
  value: 10
num_hidden_neurons:
  value: 64
num_layers:
  value: 3
optimizer:
  value: NADAM
weight_decay:
  value: 0.5
