wandb_version: 1

activation:
  value: TANH
batch_size:
  value: 32
initializer:
  value: XAVIER
learning_rate:
  value: 0.001
max_epochs:
  value: 10
num_hidden_neurons:
  value: 32
num_layers:
  value: 2
optimizer:
  value: NAG
weight_decay:
  value: 0.0005
