wandb_version: 1

activation:
  value: TANH
batch_size:
  value: 32
initializer:
  value: HE
learning_rate:
  value: 0.0001
max_epochs:
  value: 5
num_hidden_neurons:
  value: 32
num_layers:
  value: 4
optimizer:
  value: RMSPROP
weight_decay:
  value: 0.0005
