wandb_version: 1

activation:
  value: TANH
batch_size:
  value: 16
initializer:
  value: XAVIER
learning_rate:
  value: 0.0001
max_epochs:
  value: 10
num_hidden_neurons:
  value: 64
num_layers:
  value: 3
optimizer:
  value: SGD
weight_decay:
  value: 0.5
