wandb_version: 1

activation:
  value: TANH
batch_size:
  value: 64
initializer:
  value: RANDOM
learning_rate:
  value: 0.001
max_epochs:
  value: 10
num_hidden_neurons:
  value: 64
num_layers:
  value: 3
optimizer:
  value: NAG
weight_decay:
  value: 0
