wandb_version: 1

activation:
  value: SIGMOID
batch_size:
  value: 16
initializer:
  value: XAVIER
learning_rate:
  value: 0.0001
max_epochs:
  value: 5
num_hidden_neurons:
  value: 32
num_layers:
  value: 4
optimizer:
  value: ADAM
weight_decay:
  value: 0.0005
