wandb_version: 1

activation:
  value: RELU
batch_size:
  value: 16
initializer:
  value: RANDOM
learning_rate:
  value: 0.001
max_epochs:
  value: 10
num_hidden_neurons:
  value: 128
num_layers:
  value: 2
optimizer:
  value: NAG
weight_decay:
  value: 0
