wandb_version: 1

activation:
  value: SIGMOID
batch_size:
  value: 16
initializer:
  value: HE
learning_rate:
  value: 0.001
max_epochs:
  value: 5
num_hidden_neurons:
  value: 64
num_layers:
  value: 3
optimizer:
  value: NAG
weight_decay:
  value: 0.0005
