wandb_version: 1

activation_func:
  value: TANH
batch_size:
  value: 64
hidden_neurons:
  value: 128
initializer:
  value: XAVIER
layers:
  value: 3
learning_rate:
  value: 0.001
max_epochs:
  value: 5
optimizer:
  value: SGD
weight_decay:
  value: 0.0005
