wandb_version: 1

activation_func:
  value: SIGMOID
batch_size:
  value: 32
epochs:
  value: 5
hidden_neurons:
  value: 128
init_method:
  value: XAVIER
layers:
  value: 3
learning_rate:
  value: 0.001
optimizer:
  value: RMSPROP
weight_decay:
  value: 0.5
