wandb_version: 1

activation_func:
  value: TANH
batch_size:
  value: 16
epochs:
  value: 10
hidden_neurons:
  value: 32
init_method:
  value: XAVIER
layers:
  value: 2
learning_rate:
  value: 0.001
optimizer:
  value: SGD
weight_decay:
  value: 0.5
