wandb_version: 1

activation_func:
  value: RELU
batch_size:
  value: 32
epochs:
  value: 5
hidden_neurons:
  value: 64
init_method:
  value: RANDOM
layers:
  value: 3
learning_rate:
  value: 0.0001
optimizer:
  value: ADAM
weight_decay:
  value: 0.0005
