wandb_version: 1

activation_func:
  value: SIGMOID
batch_size:
  value: 32
epochs:
  value: 10
hidden_neurons:
  value: 64
init_method:
  value: XAVIER
layers:
  value: 2
learning_rate:
  value: 0.0001
optimizer:
  value: NGD
weight_decay:
  value: 0.0005
