wandb_version: 1

activation_func:
  value: SIGMOID
batch_size:
  value: 32
hidden_neurons:
  value: 32
initializer:
  value: XAVIER
layers:
  value: 4
learning_rate:
  value: 0.0001
max_epochs:
  value: 5
optimizer:
  value: MGD
weight_decay:
  value: 0.0005
