wandb_version: 1

activation:
  value: RELU
batch_size:
  value: 32
initializer:
  value: XAVIER
learning_rate:
  value: 0.001
max_epochs:
  value: 5
num_hidden_neurons:
  value: 32
num_layers:
  value: 3
optimizer:
  value: SGD
weight_decay:
  value: 0
