wandb_version: 1

activation:
  value: RELU
batch_size:
  value: 64
initializer:
  value: HE
learning_rate:
  value: 0.0001
max_epochs:
  value: 10
num_hidden_neurons:
  value: 128
num_layers:
  value: 4
optimizer:
  value: ADAM
weight_decay:
  value: 0.0005
