wandb_version: 1

activation:
  value: SIGMOID
batch_size:
  value: 64
initializer:
  value: XAVIER
learning_rate:
  value: 0.001
max_epochs:
  value: 5
num_hidden_neurons:
  value: 128
num_layers:
  value: 3
optimizer:
  value: NADAM
weight_decay:
  value: 0
