_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 16
                - 17
                - 23
                - 24
                - 55
            "4": 3.11.11
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
        visualize:
            my_bar_chart_id:
                panel_config:
                    fieldSettings:
                        label: Configuration
                        value: Test accuracy
                    panelDefId: wandb/bar/v0
                    stringSettings:
                        title: Best Configuration Test Accuracy for Fashion MNIST Classification
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: my_bar_chart_id_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
        viz:
            confusion_matrix:
                historyFieldSettings:
                    key: confusion_matrix
                    x-axis: _step
                id: wandb/confusion_matrix/v1
activation:
    value: TANH
batch_size:
    value: 64
hidden_neurons:
    value: 128
initializer:
    value: XAVIER
layers:
    value: 3
learning_rate:
    value: 0.0001
loss_function:
    value: CROSS
max_epochs:
    value: 5
optimizer:
    value: ADAM
weight_decay:
    value: 0.0005
